name: Update go
on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 12 * * WED'

jobs:
  build-and-run-tests:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      # https://github.com/actions/checkout/tree/v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Get GO version
      id: goversion
      run: echo "goversion=$(<.goversion)" > "${GITHUB_OUTPUT}"
    - name: Set up Go
      # https://github.com/actions/setup-go/tree/v5.2.0
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version: ${{steps.goversion.outputs.goversion}}
    - name: Update go
      run: ./scripts/update-go-version.sh > /tmp/go-update.log
    - name: Create pull request
      id: cpr
      # https://github.com/peter-evans/create-pull-request/releases/tag/v5.0.2
      uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
      with:
        token: ${{ secrets.UPDATE_TOKEN }}
        title: GO update
        body-path: /tmp/go-update.log
        commit-message: Automated go update
        branch: automated-go-update/patch
        delete-branch: true
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
